# fly.toml app configuration file generated for tomndips-coffee on 2024-08-25T01:23:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tomndips-coffee'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
